# Generated by Django 6.0.2 on 2026-02-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_used',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.driver'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DutyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON', 'On Duty')], max_length=10)),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='ELDLog',
        ),
        migrations.DeleteModel(
            name='TripLeg',
        ),
    ]
