# Generated by Django 6.0.2 on 2026-02-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_driver_remove_tripleg_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dutylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_logs', to='trips.trip'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
