# Generated by Django 5.0.3 on 2026-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_driver_trip_current_cycle_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
